-- ADICIONAR COLUNA PARA SERVIÇOS DE TERCEIROS NO CRM
ALTER TABLE lead_analyses ADD COLUMN IF NOT EXISTS third_party_services JSONB DEFAULT '[]';

-- ATUALIZAR SCHEMA CACHE
NOTIFY pgrst, 'reload_schema';
